#!/usr/bin/env bash
# confninit.sh — interactive first-time setup for the NixOS / home-manager config.
# Generates nixos/vars.nix from your answers.
set -euo pipefail

VARS_FILE="$(dirname "$0")/nixos/vars.nix"

# ── colours ──────────────────────────────────────────────────────────────
bold=$'\e[1m'; reset=$'\e[0m'; cyan=$'\e[36m'; green=$'\e[32m'; yellow=$'\e[33m'

header() { printf "\n${bold}${cyan}▶ %s${reset}\n" "$1"; }
ok()     { printf "  ${green}✓${reset} %s\n" "$1"; }
hint()   { printf "  ${yellow}i${reset} %s\n" "$1"; }
ask()    {
  local prompt="$1" default="$2" var_name="$3"
  printf "  ${bold}%s${reset} [${cyan}%s${reset}]: " "$prompt" "$default"
  read -r input
  printf -v "$var_name" '%s' "${input:-$default}"
}

# ── banner ────────────────────────────────────────────────────────────────
printf "\n${bold}NixOS / home-manager · config init${reset}\n"
printf "Generates %s\n" "$VARS_FILE"

# ── load existing values as defaults (if vars.nix already exists) ─────────
if [[ -f "$VARS_FILE" ]]; then
  hint "Existing vars.nix found — using its values as defaults."
  extract() { grep "$1" "$VARS_FILE" | sed 's/.*= "\(.*\)".*/\1/' | head -1; }
  cur_username="${cur_username:-$(extract 'username')}"
  cur_fullName="${cur_fullName:-$(extract 'fullName')}"
  cur_email="${cur_email:-$(extract 'email')}"
  cur_homeDir="${cur_homeDir:-$(extract 'homeDir')}"
  cur_platform="${cur_platform:-$(extract 'platform')}"
fi

cur_username="${cur_username:-$(whoami)}"
cur_fullName="${cur_fullName:-Your Full Name}"
cur_email="${cur_email:-you@example.com}"
cur_homeDir="${cur_homeDir:-/home/$(whoami)}"
cur_platform="${cur_platform:-wsl}"

# ── questions ─────────────────────────────────────────────────────────────

header "Username"
hint "Becomes your NixOS user account name and the home-manager flake key."
hint "Run 'whoami' if unsure."
ask "Username" "$cur_username" NEW_USERNAME
ok "username = \"$NEW_USERNAME\""

header "Home directory"
hint "Almost always /home/<username>. Change only for non-standard layouts."
ask "Home directory" "/home/$NEW_USERNAME" NEW_HOMEDIR
ok "homeDir = \"$NEW_HOMEDIR\""

header "Git author name"
hint "Appears in every git commit you make."
ask "Full name" "$cur_fullName" NEW_FULLNAME
ok "fullName = \"$NEW_FULLNAME\""

header "Git author email"
hint "Appears in every git commit you make."
ask "Email" "$cur_email" NEW_EMAIL
ok "email = \"$NEW_EMAIL\""

header "Platform"
hint "Controls clipboard commands and WSL-specific shell features."
hint "  wsl   = NixOS-WSL or home-manager on any WSL distro"
hint "  linux = bare Arch, bare NixOS, or any native Linux"
ask "Platform (wsl/linux)" "$cur_platform" NEW_PLATFORM
case "$NEW_PLATFORM" in
  wsl|linux) ok "platform = \"$NEW_PLATFORM\"";;
  *)
    printf "  ${yellow}Unknown platform '%s', defaulting to 'linux'${reset}\n" "$NEW_PLATFORM"
    NEW_PLATFORM="linux"
    ;;
esac

# ── write vars.nix ────────────────────────────────────────────────────────

header "Writing vars.nix"
cat > "$VARS_FILE" <<EOF
# Generated by confninit.sh — edit directly or re-run that script
{
  username = "$NEW_USERNAME";
  fullName = "$NEW_FULLNAME";
  email    = "$NEW_EMAIL";
  homeDir  = "$NEW_HOMEDIR";
  platform = "$NEW_PLATFORM"; # "wsl" | "linux"

  # Pastel Dracula palette — single source of truth for tmux, fzf, and fzf-tab
  colors = {
    purple  = "#9A348E";
    salmon  = "#DA627D";
    peach   = "#FCA17D";
    steel   = "#86BBD8";
    teal    = "#06969A";
    navy    = "#33658A";
    bg      = "#21222c";
    bgAlt   = "#44475a";
    fg      = "#f8f8f2";
    comment = "#6272a4";
  };
}
EOF
ok "Written to $VARS_FILE"

# ── next steps ────────────────────────────────────────────────────────────

printf "\n${bold}Next steps${reset}\n"
printf "  1. Commit your vars.nix:\n"
printf "       ${cyan}git add nixos/vars.nix && git commit -m 'chore: personalise vars.nix'${reset}\n\n"
printf "  2. Apply the config:\n"
if [[ "$NEW_PLATFORM" == "wsl" ]]; then
  printf "       ${cyan}home-manager switch --flake ./nixos#%s${reset}   (standalone)\n" "$NEW_USERNAME"
  printf "       ${cyan}nixos-rebuild switch --flake ./nixos#wsl${reset}  (full NixOS-WSL)\n\n"
else
  printf "       ${cyan}home-manager switch --flake ./nixos#%s${reset}\n\n" "$NEW_USERNAME"
fi
printf "  3. (Optional) Lock flake inputs for reproducibility:\n"
printf "       ${cyan}cd nixos && nix flake update && git add flake.lock && git commit -m 'chore: lock flake inputs'${reset}\n\n"
printf "  Tip: use ${cyan}nh home switch --flake ./nixos${reset} for a friendlier switch UX\n"
printf "       after the first successful build.\n\n"
