#!/usr/bin/env bash
# confninit.sh — interactive first-time setup for the NixOS / home-manager config.
# Generates nixos/vars.nix from your answers.
set -euo pipefail

VARS_FILE="$(dirname "$0")/nixos/vars.nix"
EXAMPLE_FILE="$(dirname "$0")/nixos/vars.nix.example"

# ── colours ──────────────────────────────────────────────────────────────
bold=$'\e[1m'; reset=$'\e[0m'; cyan=$'\e[36m'; green=$'\e[32m'; yellow=$'\e[33m'

header() { printf "\n${bold}${cyan}▶ %s${reset}\n" "$1"; }
ok()     { printf "  ${green}✓${reset} %s\n" "$1"; }
hint()   { printf "  ${yellow}i${reset} %s\n" "$1"; }
ask()    {
  local prompt="$1" default="$2" var_name="$3"
  printf "  ${bold}%s${reset} [${cyan}%s${reset}]: " "$prompt" "$default"
  read -r input
  printf -v "$var_name" '%s' "${input:-$default}"
}

# ── banner ────────────────────────────────────────────────────────────────
printf "\n${bold}NixOS / home-manager · config init${reset}\n"
printf "Generates %s\n" "$VARS_FILE"

# ── load existing values as defaults (if vars.nix already exists) ─────────
if [[ -f "$VARS_FILE" ]]; then
  hint "Existing vars.nix found — using its values as defaults."
  cur_username=$(grep 'username' "$VARS_FILE" | sed 's/.*= "\(.*\)".*/\1/')
  cur_fullName=$(grep 'fullName' "$VARS_FILE" | sed 's/.*= "\(.*\)".*/\1/')
  cur_email=$(grep 'email'    "$VARS_FILE" | sed 's/.*= "\(.*\)".*/\1/')
  cur_homeDir=$(grep 'homeDir' "$VARS_FILE" | sed 's/.*= "\(.*\)".*/\1/')
else
  cur_username="$(whoami)"
  cur_fullName="Your Full Name"
  cur_email="you@example.com"
  cur_homeDir="/home/$(whoami)"
fi

# ── questions ─────────────────────────────────────────────────────────────

header "Username"
hint "This becomes your NixOS user and the home-manager flake output key."
hint "Run 'whoami' if unsure."
ask "Username" "$cur_username" NEW_USERNAME
ok "username = \"$NEW_USERNAME\""

header "Home directory"
hint "Almost always /home/<username>. Change if you use a non-standard layout."
ask "Home directory" "/home/$NEW_USERNAME" NEW_HOMEDIR
ok "homeDir = \"$NEW_HOMEDIR\""

header "Git author name"
hint "Appears in every git commit you make."
ask "Full name" "$cur_fullName" NEW_FULLNAME
ok "fullName = \"$NEW_FULLNAME\""

header "Git author email"
hint "Appears in every git commit you make."
ask "Email" "$cur_email" NEW_EMAIL
ok "email = \"$NEW_EMAIL\""

# ── write vars.nix ────────────────────────────────────────────────────────

header "Writing vars.nix"
cat > "$VARS_FILE" <<EOF
# Generated by confninit.sh — edit directly or re-run that script
{
  username = "$NEW_USERNAME";
  fullName = "$NEW_FULLNAME";
  email    = "$NEW_EMAIL";
  homeDir  = "$NEW_HOMEDIR";
}
EOF
ok "Written to $VARS_FILE"

# ── next steps ────────────────────────────────────────────────────────────

printf "\n${bold}Next steps${reset}\n"
printf "  Standalone home-manager (existing install):\n"
printf "    ${cyan}home-manager switch --flake ./nixos#%s${reset}\n\n" "$NEW_USERNAME"
printf "  Full NixOS on WSL2:\n"
printf "    ${cyan}nixos-rebuild switch --flake ./nixos#wsl${reset}\n\n"
printf "  Commit your vars.nix to your personal fork so it travels with the repo:\n"
printf "    ${cyan}git add nixos/vars.nix && git commit -m 'chore: personalise vars.nix'${reset}\n\n"
